(command "CUIUNLOAD" "TAZ")
(princ "\n##############################################")
(princ "\n########## ODINSTALOWANO TOOLBAR AZ ##########")
(princ "\n##############################################")
(princ)