(defun taz_polaczenie_zal_parametry_m8 ()
  (setq taz_polaczenie_zal_parametr_s "12")
  (setq taz_polaczenie_zal_parametr_p "21")
  (setq taz_polaczenie_zal_parametr_e "11")
  (setq taz_polaczenie_zal_grubosc_blachy "8")
)

(defun taz_polaczenie_zal_parametry_m10 ()
  (setq taz_polaczenie_zal_parametr_s "15")
  (setq taz_polaczenie_zal_parametr_p "25")
  (setq taz_polaczenie_zal_parametr_e "13")
  (setq taz_polaczenie_zal_grubosc_blachy "10")
)

(defun taz_polaczenie_zal_parametry_m12 ()
  (setq taz_polaczenie_zal_parametr_s "18")
  (setq taz_polaczenie_zal_parametr_p "30")
  (setq taz_polaczenie_zal_parametr_e "16")
  (setq taz_polaczenie_zal_grubosc_blachy "12")
)

(defun taz_polaczenie_zal_parametry_m16 ()
  (setq taz_polaczenie_zal_parametr_s "24")
  (setq taz_polaczenie_zal_parametr_p "41")
  (setq taz_polaczenie_zal_parametr_e "22")
  (setq taz_polaczenie_zal_grubosc_blachy "15")
)

(defun taz_polaczenie_zal_parametry_m20 ()
  (setq taz_polaczenie_zal_parametr_s "30")
  (setq taz_polaczenie_zal_parametr_p "50")
  (setq taz_polaczenie_zal_parametr_e "26")
  (setq taz_polaczenie_zal_grubosc_blachy "20")
)

(defun taz_polaczenie_zal_parametry_m24 ()
  (setq taz_polaczenie_zal_parametr_s "36")
  (setq taz_polaczenie_zal_parametr_p "60")
  (setq taz_polaczenie_zal_parametr_e "31")
  (setq taz_polaczenie_zal_grubosc_blachy "20")
)

(defun taz_polaczenie_zal_parametry_m30 ()
  (setq taz_polaczenie_zal_parametr_s "45")
  (setq taz_polaczenie_zal_parametr_p "75")
  (setq taz_polaczenie_zal_parametr_e "39")
  (setq taz_polaczenie_zal_grubosc_blachy "20")
)

(defun taz_polaczenie_zakladkowe_parametry ()
  (setq taz_polaczenie_zakladkowe_rodzaj_sruby (getstring (strcat "\nPodaj srednice trzpienia sruby (MXX) [8/10/12/16/20/24/30]: <" taz_aktualne_polaczenie_zakladkowe_rodzaj_sruby ">")))
  (if (equal taz_polaczenie_zakladkowe_rodzaj_sruby "")
      (setq taz_polaczenie_zakladkowe_rodzaj_sruby taz_aktualne_polaczenie_zakladkowe_rodzaj_sruby)
      (princ)
  )
  (setq taz_aktualne_polaczenie_zakladkowe_rodzaj_sruby taz_polaczenie_zakladkowe_rodzaj_sruby)
  (if (equal taz_polaczenie_zakladkowe_rodzaj_sruby "8")
      (taz_polaczenie_zal_parametry_m8)
      (princ)
  )
  (if (equal taz_polaczenie_zakladkowe_rodzaj_sruby "10")
      (taz_polaczenie_zal_parametry_m10)
      (princ)
  )
  (if (equal taz_polaczenie_zakladkowe_rodzaj_sruby "12")
      (taz_polaczenie_zal_parametry_m12)
      (princ)
  )
  (if (equal taz_polaczenie_zakladkowe_rodzaj_sruby "16")
      (taz_polaczenie_zal_parametry_m16)
      (princ)
  )
    (if (equal taz_polaczenie_zakladkowe_rodzaj_sruby "20")
      (taz_polaczenie_zal_parametry_m20)
      (princ)
  )
  (if (equal taz_polaczenie_zakladkowe_rodzaj_sruby "24")
      (taz_polaczenie_zal_parametry_m24)
      (princ)
  )
  (if (equal taz_polaczenie_zakladkowe_rodzaj_sruby "30")
      (taz_polaczenie_zal_parametry_m30)
      (princ)
  )
  
  (setq taz_polaczenie_parametr_p (getstring (strcat "\nPodaj rozstaw srub: <" taz_polaczenie_zal_parametr_p ">")))
  (if (equal taz_polaczenie_parametr_p "")
      (setq taz_polaczenie_parametr_p taz_polaczenie_zal_parametr_p)
      (princ)
  )

  (setq taz_polaczenie_parametr_s (getstring (strcat "\nPodaj odleglosc do lica elementu: <" taz_polaczenie_zal_parametr_s ">")))
  (if (equal taz_polaczenie_parametr_s "")
      (setq taz_polaczenie_parametr_s taz_polaczenie_zal_parametr_s)
      (princ)
  )
  
  (setq taz_polaczenie_parametr_e (getstring (strcat "\nPodaj odleglosc do krawedzi blachy: <" taz_polaczenie_zal_parametr_e ">")))
  (if (equal taz_polaczenie_parametr_e "")
      (setq taz_polaczenie_parametr_e taz_polaczenie_zal_parametr_e)
      (princ)
  )
  (princ)
)

(defun taz_polaczenie_zakladkowe_widok ( / *error* )
  (defun *error* ( taz_przyczyna_bledu )
    (command)(command)
	(command "_erase" taz_polaczenie_zakladkowe_scalenie "")
    (setq taz_polaczenie_zakladkowe_scalenie (ssadd))
    (command "_UCS" "_P")
    (command "_layer" "_S" taz_aktualna_warstwa "")
    (princ)
  )
  (command "_UCS" "_W")
  (setq taz_aktualna_warstwa (getvar "CLAYER"))
  (taz_polaczenie_zakladkowe_parametry)
  
  (setq taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie (getstring (strcat "\nPodaj ilosc srub w polaczeniu poziomo: <" taz_aktualne_polaczenie_zakladkowe_ilosc_srub_w_poziomie ">")))
  (if (equal taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie "")
      (setq taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie taz_aktualne_polaczenie_zakladkowe_ilosc_srub_w_poziomie)
      (princ)
  )
  
  (setq taz_polaczenie_zakladkowe_ilosc_srub_w_pionie (getstring (strcat "\nPodaj ilosc srub w polaczeniu pionowo: <" taz_aktualne_polaczenie_zakladkowe_ilosc_srub_w_pionie ">")))
  (if (equal taz_polaczenie_zakladkowe_ilosc_srub_w_pionie "")
      (setq taz_polaczenie_zakladkowe_ilosc_srub_w_pionie taz_aktualne_polaczenie_zakladkowe_ilosc_srub_w_pionie)
      (princ)
  )
  
  (setq taz_polaczenie_zakladkowe_widok_punkt_wstawienia (getpoint "\nWskaz punkt wstawienia polaczenia: "))
  
  (setq taz_polaczenie_zakladkowe_scalenie (ssadd))
  
  ;######### OTWORY #########
  (command "_ZOOM" "_SCALE" "10000X")
  (command "_layer" "_S" "TAZ_AXIS" "")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punkty "0")
  (repeat (atoi taz_polaczenie_zakladkowe_ilosc_srub_w_pionie)
    (setq taz_polaczenie_zakladkowe_aktualny_punktx "0")
    (repeat (atoi taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie)
      (command "_point" (list (atoi taz_polaczenie_zakladkowe_aktualny_punktx) (atoi taz_polaczenie_zakladkowe_aktualny_punkty))) (ssadd (entlast) taz_polaczenie_zakladkowe_scalenie)
      (setq taz_polaczenie_zakladkowe_srodek (list (/ (cadr (assoc 10 (entget (entlast)))) 2) (/ (caddr (assoc 10 (entget (entlast)))) 2)))
      (setq taz_polaczenie_zakladkowe_aktualny_punktx (itoa (+ (atoi taz_polaczenie_zakladkowe_aktualny_punktx) (atoi taz_polaczenie_parametr_p))))
    )
    (setq taz_polaczenie_zakladkowe_aktualny_punkty (itoa (+ (atoi taz_polaczenie_zakladkowe_aktualny_punkty) (atoi taz_polaczenie_parametr_p))))
  )
  
  ;######### KRAWEDZ ELEMENTU #########
  (command "_layer" "_S" "TAZ_SECTION" "")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx1 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punkty1 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx2 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punkty2 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx1 (itoa (- (atoi taz_polaczenie_zakladkowe_aktualny_punktx1) (atoi taz_polaczenie_parametr_s))))
  (setq taz_polaczenie_zakladkowe_aktualny_punkty1 (itoa (- (atoi taz_polaczenie_zakladkowe_aktualny_punkty1) (atoi taz_polaczenie_parametr_s))))
  (setq taz_polaczenie_zakladkowe_aktualny_punktx2 (itoa (+ (* (+ (atoi taz_polaczenie_zakladkowe_aktualny_punktx2) (atoi taz_polaczenie_parametr_p)) (1- (atoi taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie))) (atoi taz_polaczenie_parametr_s))))
  (setq taz_polaczenie_zakladkowe_aktualny_punkty2 (itoa (+ (* (+ (atoi taz_polaczenie_zakladkowe_aktualny_punkty2) (atoi taz_polaczenie_parametr_p)) (1- (atoi taz_polaczenie_zakladkowe_ilosc_srub_w_pionie))) (atoi taz_polaczenie_parametr_s))))
  (command "_rectang" (list (atoi taz_polaczenie_zakladkowe_aktualny_punktx1) (atoi taz_polaczenie_zakladkowe_aktualny_punkty1)) (list (atoi taz_polaczenie_zakladkowe_aktualny_punktx2) (atoi taz_polaczenie_zakladkowe_aktualny_punkty2))) (ssadd (entlast) taz_polaczenie_zakladkowe_scalenie)


  ;######### KRAWEDZ BLACHY #########
  (command "_layer" "_S" "TAZ_VIEW" "")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx1 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punkty1 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx2 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punkty2 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx1 (itoa (- (atoi taz_polaczenie_zakladkowe_aktualny_punktx1) (atoi taz_polaczenie_parametr_e))))
  (setq taz_polaczenie_zakladkowe_aktualny_punkty1 (itoa (- (atoi taz_polaczenie_zakladkowe_aktualny_punkty1) (atoi taz_polaczenie_parametr_e))))
  (setq taz_polaczenie_zakladkowe_aktualny_punktx2 (itoa (+ (* (+ (atoi taz_polaczenie_zakladkowe_aktualny_punktx2) (atoi taz_polaczenie_parametr_p)) (1- (atoi taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie))) (atoi taz_polaczenie_parametr_e))))
  (setq taz_polaczenie_zakladkowe_aktualny_punkty2 (itoa (+ (* (+ (atoi taz_polaczenie_zakladkowe_aktualny_punkty2) (atoi taz_polaczenie_parametr_p)) (1- (atoi taz_polaczenie_zakladkowe_ilosc_srub_w_pionie))) (atoi taz_polaczenie_parametr_e))))
  (command "_rectang" (list (atoi taz_polaczenie_zakladkowe_aktualny_punktx1) (atoi taz_polaczenie_zakladkowe_aktualny_punkty1)) (list (atoi taz_polaczenie_zakladkowe_aktualny_punktx2) (atoi taz_polaczenie_zakladkowe_aktualny_punkty2))) (ssadd (entlast) taz_polaczenie_zakladkowe_scalenie)
  (command "_ZOOM" "_SCALE" "0.0001X")
  (command "_group" "_C" "*" "" taz_polaczenie_zakladkowe_scalenie "")
  (command "_move" taz_polaczenie_zakladkowe_scalenie "" taz_polaczenie_zakladkowe_srodek taz_polaczenie_zakladkowe_widok_punkt_wstawienia)
  (setq taz_polaczenie_zakladkowe_scalenie (ssadd))
  (command "_UCS" "_P")
  (command "_layer" "_S" taz_aktualna_warstwa "")
  (princ)
)

(defun taz_polaczenie_zakladkowe_przekroj ( / *error* )
  (defun *error* ( taz_przyczyna_bledu )
    (command)(command)
	(command "_erase" taz_polaczenie_zakladkowe_scalenie "")
    (setq taz_polaczenie_zakladkowe_scalenie (ssadd))
    (command "_UCS" "_P")
    (command "_layer" "_S" taz_aktualna_warstwa "")
    (princ)
  )
  (command "_UCS" "_W")
  (setq taz_aktualna_warstwa (getvar "CLAYER"))
  (taz_polaczenie_zakladkowe_parametry)
  
  (setq taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie (getstring (strcat "\nPodaj ilosc srub w polaczeniu poziomo: <" taz_aktualne_polaczenie_zakladkowe_ilosc_srub_w_poziomie ">")))
  (if (equal taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie "")
      (setq taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie taz_aktualne_polaczenie_zakladkowe_ilosc_srub_w_poziomie)
      (princ)
  )
  
  (setq taz_polaczenie_grubosc_blachy (getstring (strcat "\nPodaj sumaryczna grubosc blach w polaczeniu: <" taz_polaczenie_zal_grubosc_blachy ">")))
  (if (equal taz_polaczenie_grubosc_blachy "")
      (setq taz_polaczenie_grubosc_blachy taz_polaczenie_zal_grubosc_blachy)
      (princ)
  )
  
  (setq taz_polaczenie_zakladkowe_przekroj_punkt_wstawienia (getpoint "\nWskaz punkt wstawienia polaczenia: "))
  
  (setq taz_polaczenie_zakladkowe_scalenie (ssadd))
  
  ;######### OTWORY #########
  (command "_ZOOM" "_SCALE" "10000X")
  (command "_layer" "_S" "TAZ_AXIS" "")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punkty "0")
  
    (repeat (atoi taz_polaczenie_zakladkowe_ilosc_srub_w_poziomie)
      (command "_pline" (list (atoi taz_polaczenie_zakladkowe_aktualny_punktx) (- (atoi taz_polaczenie_zakladkowe_aktualny_punkty) (/ (atoi taz_polaczenie_grubosc_blachy) 2))) (list (atoi taz_polaczenie_zakladkowe_aktualny_punktx) (+ (atoi taz_polaczenie_zakladkowe_aktualny_punkty) (/ (atoi taz_polaczenie_grubosc_blachy) 2))) "") (ssadd (entlast) taz_polaczenie_zakladkowe_scalenie)
      (setq taz_polaczenie_zakladkowe_srodek (list (/ (cadr (assoc 10 (entget (entlast)))) 2) 0))
      (setq taz_polaczenie_zakladkowe_aktualny_koncowy_punktx (itoa (atoi taz_polaczenie_zakladkowe_aktualny_punktx)))
      (setq taz_polaczenie_zakladkowe_aktualny_punktx (itoa (+ (atoi taz_polaczenie_zakladkowe_aktualny_punktx) (atoi taz_polaczenie_parametr_p))))
    )
  
  ;######### KRAWEDZ BLACHY #########
  (command "_layer" "_S" "TAZ_VIEW" "")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx1 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punkty1 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx2 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punkty2 "0")
  (setq taz_polaczenie_zakladkowe_aktualny_punktx1 (itoa (- (atoi taz_polaczenie_zakladkowe_aktualny_punktx1) (atoi taz_polaczenie_parametr_e))))
  (setq taz_polaczenie_zakladkowe_aktualny_punkty1 (itoa (- (atoi taz_polaczenie_zakladkowe_aktualny_punkty1) (/ (atoi taz_polaczenie_grubosc_blachy) 2))))
  (setq taz_polaczenie_zakladkowe_aktualny_punktx2 (itoa (+ (atoi taz_polaczenie_zakladkowe_aktualny_koncowy_punktx) (atoi taz_polaczenie_parametr_e))))
  (setq taz_polaczenie_zakladkowe_aktualny_punkty2 (itoa (* (atoi taz_polaczenie_zakladkowe_aktualny_punkty1) -1)))
  (command "_rectang" (list (atoi taz_polaczenie_zakladkowe_aktualny_punktx1) (atoi taz_polaczenie_zakladkowe_aktualny_punkty1)) (list (atoi taz_polaczenie_zakladkowe_aktualny_punktx2) (atoi taz_polaczenie_zakladkowe_aktualny_punkty2))) (ssadd (entlast) taz_polaczenie_zakladkowe_scalenie)
  (command "_ZOOM" "_SCALE" "0.0001X")
  (command "_group" "_C" "*" "" taz_polaczenie_zakladkowe_scalenie "")
  (command "_move" taz_polaczenie_zakladkowe_scalenie "" taz_polaczenie_zakladkowe_srodek taz_polaczenie_zakladkowe_przekroj_punkt_wstawienia)
  (setq taz_polaczenie_zakladkowe_scalenie (ssadd))
  (command "_UCS" "_P")
  (command "_layer" "_S" taz_aktualna_warstwa "")
  (princ)
)